apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: cp4a-git-infra 
spec:
  type: git
  params:
    - name: revision
      value: master 
    - name: url
      value: https://github.com/ogaye-ibm/dillards-infra.git

---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
    name: cp4a-git
spec:
    type: git
    params:
      - name: revision
        value: master
      - name: url
        value: https://github.com/ogaye-ibm/dillards-springboot.git
    
